apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: scratch
  name: scratch
spec:
  replicas: 0
  selector:
    matchLabels:
      run: scratch
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 65535
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: scratch
    spec:
      containers:
      - image: scratch
        imagePullPolicy: Always
        name: scratch
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
